ros_domain_id: 0
namespace: ""
pkg_robot_description: "my_robot_description_pkg"
robot_description: "urdf/my_robot.urdf"
display_on: "both"
use_sim_time: false
rviz:
  config: "config/rviz.yaml"
gazebo:
  mode: "both"
  world: "worlds/my_world.sdf"
  robot_position: [0, 0, 0, 0, 0, 0]
  spawn_models:
    - [ "models/model1.sdf", "model1", 1.0, 1.0, 0.0, 0.0, 0.0, 0.0 ]
    - [ "models/model2.sdf", "model2", 2.0, 2.0, 0.0, 0.0, 0.0, 0.0 ]
  autorun: false
